[package]
name = "apply_git_summary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lscolors = "0.20.0"
nu-ansi-term = { version = "0.50", optional = true }
